#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 1086653911098-j03aimqelt9cltgtta1cib22ehnotove.apps.googleusercontent.com
#            client-secret: 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
#            scope:
#              - profile
#              - email