version: "3" # 버전 지정

services: # 컨테이너 설정
  database:
    container_name: gJIW9xePh7OuXhP7JkXMAFBQ/c8n2+N9qTD0s8mCZGA= # 컨테이너 이름
    image: mysql/mysql-server:latest # 컨테이너에서 사용하는 base image 지정
    environment: # 컨테이너 안의 환경변수 설정
      MYSQL_DATABASE: ENC(C1kh7Xd6dWdcXy2hn2SRBw==)
      MYSQL_USER: ENC(O1S4H5LxwL5mybbXN/tZTA==)
      MYSQL_PASSWORD: ENC(jujp25bgXsJ6ZHabdoFtC7KD9c95owEG)
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: ENC(XXVfRZEA5tqsj4PGfToyvJNcE7WQrfki)
    command: # 명령어 설정
      - --default-authentication-plugin=mysql_native_password
    ports: # 접근 포트 설정
      - 3305:3306 # Host:Container
    networks:
      - db_network
    restart: always  # 컨테이너 실행 시 재시작
  mytamla:
    build: .
    expose:
      - 8080
    depends_on:
      - database

networks: # 커스텀 네트워크 추가
  db_network: # 네트워크 이름
    driver: bridge